name: remove others

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'todo/**'
      
defaults:
  run:
    working-directory: todo

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  remove:
    runs-on:
      windows-latest
    steps:
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Check Out
      uses: actions/checkout@v2.3.5
   
    
  Push_to_S3:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: s3 push
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'out'
